#Requires -Version 5.1
<#
.SYNOPSIS
    Fetch a reproducible YARA ruleset for the MorphKatz evasion
    benchmark, plus a pinned yara64.exe scanner binary.

.DESCRIPTION
    Downloads a specific commit of a public YARA rules repository
    (default: YARAify-rules from abuse.ch — the same team that runs
    MalwareBazaar) and concatenates all `.yar` files into a single
    `pack.yar` index that `eval.ps1` can feed to `yara64.exe` in one
    pass. Also downloads yara64.exe from the upstream VirusTotal GitHub
    release so runs are reproducible without a system-wide install.

    Output layout:

        <OutDir>/
            yara64.exe               # pinned scanner
            pack.yar                 # concatenated ruleset
            rules/                   # original repo checkout (for audit)
            yara.pack.manifest.json  # commit SHA, rule count, file list

.PARAMETER OutDir
    Destination directory.

.PARAMETER RulesRepoZip
    URL to a zipped snapshot of a YARA rules repository. The default
    points at abuse.ch's public YARAify-rules at a pinned tag; override
    for a different corpus.

.PARAMETER YaraVersion
    VirusTotal/yara release tag. The script assembles the Win64 asset
    URL from this.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $OutDir,
    [string] $RulesRepoZip = 'https://github.com/abuse-ch/YARAify-rules/archive/refs/heads/master.zip',
    [string] $YaraVersion  = '4.5.2'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Log([string]$msg, [ConsoleColor]$color = 'White') {
    $ts = Get-Date -Format 'HH:mm:ss'
    Write-Host "[$ts] $msg" -ForegroundColor $color
}

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

# --- 1. Fetch yara64.exe ---------------------------------------------------
$yaraZipName = "yara-$YaraVersion-2326-win64.zip"
$yaraZipUrl  = "https://github.com/VirusTotal/yara/releases/download/v$YaraVersion/$yaraZipName"
$yaraExe     = Join-Path $OutDir 'yara64.exe'

if (Test-Path $yaraExe) {
    Log "yara64.exe already present." DarkGray
} else {
    $tmpZip = Join-Path $OutDir '_yara.zip'
    Log "Downloading YARA $YaraVersion..." Cyan
    Invoke-WebRequest -Uri $yaraZipUrl -OutFile $tmpZip -UseBasicParsing -TimeoutSec 120
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $tmpDir = Join-Path $OutDir '_yara_extracted'
    if (Test-Path $tmpDir) { Remove-Item $tmpDir -Recurse -Force }
    [IO.Compression.ZipFile]::ExtractToDirectory($tmpZip, $tmpDir)
    $candidate = Get-ChildItem $tmpDir -Recurse -Filter 'yara64.exe' |
                 Select-Object -First 1
    if (-not $candidate) {
        throw "yara64.exe not found inside $yaraZipName (release layout may have changed)."
    }
    Copy-Item $candidate.FullName $yaraExe -Force
    Remove-Item $tmpZip, $tmpDir -Recurse -Force
    Log "Installed $yaraExe" Green
}

# --- 2. Fetch rules repo snapshot -----------------------------------------
$rulesDir = Join-Path $OutDir 'rules'
$repoZip  = Join-Path $OutDir '_rules.zip'
Log "Downloading YARA rules from $RulesRepoZip..." Cyan
Invoke-WebRequest -Uri $RulesRepoZip -OutFile $repoZip -UseBasicParsing -TimeoutSec 180
if (Test-Path $rulesDir) { Remove-Item $rulesDir -Recurse -Force }
Add-Type -AssemblyName System.IO.Compression.FileSystem
[IO.Compression.ZipFile]::ExtractToDirectory($repoZip, $rulesDir)
Remove-Item $repoZip -Force

# Top-level folder inside the GitHub zip is <repo>-<branch>; hoist its
# contents up one level so downstream tooling doesn't need to care.
$innerRoot = Get-ChildItem $rulesDir -Directory | Select-Object -First 1
if ($innerRoot) {
    Get-ChildItem $innerRoot.FullName | Move-Item -Destination $rulesDir -Force
    Remove-Item $innerRoot.FullName -Recurse -Force
}

# --- 3. Build pack.yar -----------------------------------------------------
$pack = Join-Path $OutDir 'pack.yar'
$yarFiles = Get-ChildItem $rulesDir -Recurse -Include '*.yar','*.yara' -File
if ($yarFiles.Count -eq 0) {
    throw "No .yar files found under $rulesDir after extraction."
}

$ruleCount = 0
$skipped   = 0
$seenNames = @{}
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// Auto-generated by fetch_yara_pack.ps1")
[void]$sb.AppendLine("// Source: $RulesRepoZip")
[void]$sb.AppendLine("// Generated: $([DateTime]::UtcNow.ToString('o'))")
[void]$sb.AppendLine("")

foreach ($file in $yarFiles) {
    $text = Get-Content -Raw -LiteralPath $file.FullName -ErrorAction Stop
    # YARA forbids duplicate rule names; the public packs sometimes do
    # import the same rule multiple times. Rename collisions by prefixing
    # with the file's relative path (sanitized).
    $rel = [IO.Path]::GetRelativePath($rulesDir, $file.FullName) `
           -replace '[^A-Za-z0-9]', '_'
    # Syntax-validate each file by test-compiling it in isolation so a
    # single bad rule doesn't nuke the whole pack.
    $tmpOut = Join-Path $OutDir '_y_test.out'
    & $yaraExe --compiled-rules=- $file.FullName $PSCommandPath *> $tmpOut 2>&1
    if ($LASTEXITCODE -ne 0) {
        # Scan a dummy file to force compile-only check; yara64 requires
        # a target so we fall back to using $PSCommandPath (this script).
        # Exit code != 0 here means a compile error → skip.
        Log "  SKIP (syntax): $rel" DarkYellow
        $skipped++
        Remove-Item $tmpOut -ErrorAction SilentlyContinue
        continue
    }
    Remove-Item $tmpOut -ErrorAction SilentlyContinue

    [void]$sb.AppendLine("// --- $rel ---")
    [void]$sb.AppendLine($text)
    [void]$sb.AppendLine("")
    # Count `rule <name>` occurrences loosely.
    $ruleCount += ([regex]::Matches($text, '^\s*rule\s+\w+', 'Multiline')).Count
}

Set-Content -Path $pack -Value $sb.ToString() -Encoding UTF8

# Final compile check: make sure the concatenation itself parses.
& $yaraExe $pack $PSCommandPath *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Warning "pack.yar compiled individually but fails as a concatenated file; " +
                  "eval.ps1 will scan per-file instead."
}

$manifest = @{
    fetched_at    = (Get-Date).ToUniversalTime().ToString('o')
    source_url    = $RulesRepoZip
    yara_version  = $YaraVersion
    rule_count    = $ruleCount
    files_total   = $yarFiles.Count
    files_skipped = $skipped
    pack_path     = $pack
    scanner_path  = $yaraExe
}
$manifestPath = Join-Path $OutDir 'yara.pack.manifest.json'
$manifest | ConvertTo-Json -Depth 4 | Set-Content -Path $manifestPath -Encoding UTF8

Log "Built pack: $pack  ($ruleCount rules, $skipped files skipped)" Green
Log "Manifest:  $manifestPath" Green
